/**
 * The block registry — what the Insert panel offers.
 *
 * Blocks are grouped rather than listed. Nine fitted in a flat column; the
 * library this grows into does not, and a designer looking for a pricing table
 * should not have to read past thirty other names to find it.
 */

import type { NodeSpec } from '../../document/factory';

export * from './kit';
export {
  announcementSpec,
  breadcrumbsSpec,
  docsLayoutSpec,
  footerSpec,
  minimalFooterSpec,
  navMenuSpec,
  navbarSpec,
  subNavSpec,
} from './chrome';
export {
  deviceHeroSpec,
  heroSectionSpec,
  mediaHeroSpec,
  productShotSpec,
  splitHeroSpec,
  videoHeroSpec,
} from './hero';
export {
  caseStudiesSpec,
  logoCloudSpec,
  logoGridSpec,
  portraitQuoteSpec,
  pullQuoteSpec,
  ratingsSpec,
  statsSpec,
  testimonialsSpec,
} from './proof';
export {
  alternatingFeaturesSpec,
  bentoFeaturesSpec,
  checklistSpec,
  featureSectionSpec,
  integrationsSpec,
  processStepsSpec,
  tabbedFeaturesSpec,
  timelineSpec,
} from './features';
export { ctaSpec, ctaSplitSpec, pricingSpec, pricingSwitchSpec } from './convert';
export {
  alertsSpec,
  appShellSpec,
  authSpec,
  badgesSpec,
  commandMenuSpec,
  comparisonSpec,
  confirmDialogSpec,
  dataTableSpec,
  emptyStateSpec,
  fileListSpec,
  filterPanelSpec,
  formSpec,
  membersSpec,
  notificationsSpec,
  searchBarSpec,
  settingsSpec,
  skeletonSpec,
  statCardsSpec,
  stepperSpec,
  uploadSpec,
} from './app';
export {
  cartSummarySpec,
  productDetailSpec,
  productGridSpec,
  shippingStripSpec,
} from './commerce';
export {
  articleSpec,
  authorCardSpec,
  blogHeaderSpec,
  featuredPostSpec,
  installTabsSpec,
  paginationSpec,
  postGridSpec,
  relatedPostsSpec,
} from './editorial';
export {
  faqAccordionSpec,
  faqSpec,
  gallerySpec,
  masonrySpec,
  proseSpec,
  rolesSpec,
  teamSpec,
  workFilterSpec,
} from './trust';

import {
  announcementSpec,
  breadcrumbsSpec,
  docsLayoutSpec,
  footerSpec,
  minimalFooterSpec,
  navMenuSpec,
  navbarSpec,
  subNavSpec,
} from './chrome';
import { ctaSpec, ctaSplitSpec, pricingSpec, pricingSwitchSpec } from './convert';
import {
  alertsSpec,
  appShellSpec,
  authSpec,
  badgesSpec,
  commandMenuSpec,
  comparisonSpec,
  confirmDialogSpec,
  dataTableSpec,
  emptyStateSpec,
  fileListSpec,
  filterPanelSpec,
  formSpec,
  membersSpec,
  notificationsSpec,
  searchBarSpec,
  settingsSpec,
  skeletonSpec,
  statCardsSpec,
  stepperSpec,
  uploadSpec,
} from './app';
import {
  cartSummarySpec,
  productDetailSpec,
  productGridSpec,
  shippingStripSpec,
} from './commerce';
import {
  articleSpec,
  authorCardSpec,
  blogHeaderSpec,
  featuredPostSpec,
  installTabsSpec,
  paginationSpec,
  postGridSpec,
  relatedPostsSpec,
} from './editorial';
import {
  alternatingFeaturesSpec,
  bentoFeaturesSpec,
  checklistSpec,
  featureSectionSpec,
  integrationsSpec,
  processStepsSpec,
  tabbedFeaturesSpec,
  timelineSpec,
} from './features';
import {
  deviceHeroSpec,
  heroSectionSpec,
  mediaHeroSpec,
  splitHeroSpec,
  videoHeroSpec,
} from './hero';
import {
  caseStudiesSpec,
  logoCloudSpec,
  logoGridSpec,
  portraitQuoteSpec,
  pullQuoteSpec,
  ratingsSpec,
  statsSpec,
  testimonialsSpec,
} from './proof';
import {
  faqAccordionSpec,
  faqSpec,
  gallerySpec,
  masonrySpec,
  proseSpec,
  rolesSpec,
  teamSpec,
  workFilterSpec,
} from './trust';

export type BlockCategory =
  | 'chrome'
  | 'hero'
  | 'proof'
  | 'features'
  | 'convert'
  | 'trust'
  | 'editorial'
  | 'commerce'
  | 'app';

export const BLOCK_CATEGORIES: { id: BlockCategory; label: string }[] = [
  { id: 'chrome', label: 'Header & footer' },
  { id: 'hero', label: 'Hero' },
  { id: 'features', label: 'Features' },
  { id: 'proof', label: 'Social proof' },
  { id: 'convert', label: 'Conversion' },
  { id: 'trust', label: 'Trust' },
  { id: 'editorial', label: 'Editorial' },
  { id: 'commerce', label: 'Commerce' },
  { id: 'app', label: 'Application' },
];

export interface BlockDefinition {
  id: string;
  name: string;
  description: string;
  category: BlockCategory;
  /** Extra search terms — what someone might type that isn't in the name. */
  keywords?: string[];
  build: () => NodeSpec;
}

export const BLOCKS: BlockDefinition[] = [
  {
    id: 'nav-menu',
    name: 'Navbar with menu',
    description: 'Links collapse into a menu the browser opens',
    category: 'chrome',
    keywords: ['header', 'hamburger', 'mobile', 'popover', 'nav', 'responsive'],
    build: navMenuSpec,
  },
  {
    id: 'navbar',
    name: 'Navbar',
    description: 'Sticky header with links and a CTA',
    category: 'chrome',
    keywords: ['header', 'menu', 'navigation', 'top bar'],
    build: navbarSpec,
  },
  {
    id: 'footer',
    name: 'Footer',
    description: 'Link columns and legal line',
    category: 'chrome',
    keywords: ['sitemap', 'legal', 'bottom'],
    build: footerSpec,
  },
  {
    id: 'announcement',
    name: 'Announcement bar',
    description: 'Thin strip above the header',
    category: 'chrome',
    keywords: ['banner', 'notice', 'promo', 'strip', 'news'],
    build: announcementSpec,
  },
  {
    id: 'breadcrumbs',
    name: 'Breadcrumbs',
    description: 'Trail showing where the page sits',
    category: 'chrome',
    keywords: ['trail', 'path', 'hierarchy', 'navigation'],
    build: breadcrumbsSpec,
  },
  {
    id: 'subnav',
    name: 'Sub navigation',
    description: 'Tab row under the header',
    category: 'chrome',
    keywords: ['tabs', 'sections', 'secondary', 'navigation'],
    build: subNavSpec,
  },
  {
    id: 'docs-layout',
    name: 'Docs layout',
    description: 'Sticky sidebar beside an article',
    category: 'chrome',
    keywords: ['documentation', 'sidebar', 'article', 'reference', 'guide'],
    build: docsLayoutSpec,
  },
  {
    id: 'footer-minimal',
    name: 'Minimal footer',
    description: 'One row of links, with back to top',
    category: 'chrome',
    keywords: ['simple', 'small', 'bottom', 'compact'],
    build: minimalFooterSpec,
  },
  {
    id: 'hero',
    name: 'Hero',
    description: 'Headline, subtext, buttons and a product shot',
    category: 'hero',
    keywords: ['banner', 'above the fold', 'headline', 'screenshot'],
    build: heroSectionSpec,
  },
  {
    id: 'features',
    name: 'Feature grid',
    description: 'Three-column feature cards',
    category: 'features',
    keywords: ['benefits', 'cards', 'icons', 'grid'],
    build: featureSectionSpec,
  },
  {
    id: 'hero-split',
    name: 'Split hero',
    description: 'Copy beside a product screenshot',
    category: 'hero',
    keywords: ['two column', 'screenshot', 'side by side', 'above the fold'],
    build: splitHeroSpec,
  },
  {
    id: 'hero-media',
    name: 'Photo hero',
    description: 'Full-bleed photograph behind centred copy',
    category: 'hero',
    keywords: ['background', 'image', 'full bleed', 'cover', 'banner'],
    build: mediaHeroSpec,
  },
  {
    id: 'hero-device',
    name: 'Device hero',
    description: 'Copy beside a phone mock-up',
    category: 'hero',
    keywords: ['mobile', 'app', 'phone', 'ios', 'android'],
    build: deviceHeroSpec,
  },
  {
    id: 'hero-video',
    name: 'Video hero',
    description: 'Headline above a wide video player',
    category: 'hero',
    keywords: ['film', 'demo', 'player', 'watch'],
    build: videoHeroSpec,
  },
  {
    id: 'features-alternating',
    name: 'Alternating rows',
    description: 'Copy and screenshot, zig-zagging down the page',
    category: 'features',
    keywords: ['zigzag', 'split', 'screenshot', 'side by side'],
    build: alternatingFeaturesSpec,
  },
  {
    id: 'features-bento',
    name: 'Bento grid',
    description: 'Mixed-width cards in an asymmetric grid',
    category: 'features',
    keywords: ['mosaic', 'asymmetric', 'cards', 'tiles'],
    build: bentoFeaturesSpec,
  },
  {
    id: 'features-checklist',
    name: 'Checklist',
    description: 'Two columns of ticked capabilities',
    category: 'features',
    keywords: ['list', 'included', 'ticks', 'capabilities'],
    build: checklistSpec,
  },
  {
    id: 'features-steps',
    name: 'Process steps',
    description: 'Numbered steps across four columns',
    category: 'features',
    keywords: ['how it works', 'onboarding', 'numbered', 'getting started'],
    build: processStepsSpec,
  },
  {
    id: 'features-timeline',
    name: 'Timeline',
    description: 'Milestones on a vertical rail',
    category: 'features',
    keywords: ['roadmap', 'changelog', 'history', 'milestones'],
    build: timelineSpec,
  },
  {
    id: 'features-integrations',
    name: 'Integrations',
    description: 'Directory grid of connected tools',
    category: 'features',
    keywords: ['apps', 'directory', 'partners', 'connect'],
    build: integrationsSpec,
  },
  {
    id: 'logos',
    name: 'Logo cloud',
    description: 'Social proof row',
    category: 'proof',
    keywords: ['customers', 'brands', 'trusted by', 'clients'],
    build: logoCloudSpec,
  },
  {
    id: 'testimonials',
    name: 'Testimonials',
    description: 'Customer quotes with avatars',
    category: 'proof',
    keywords: ['quotes', 'reviews', 'customers', 'social proof'],
    build: testimonialsSpec,
  },
  {
    id: 'logos-grid',
    name: 'Logo grid',
    description: 'Bordered cells in a hairline lattice',
    category: 'proof',
    keywords: ['customers', 'brands', 'clients', 'lattice', 'cells'],
    build: logoGridSpec,
  },
  {
    id: 'stats',
    name: 'Stats band',
    description: 'Four headline numbers',
    category: 'proof',
    keywords: ['metrics', 'numbers', 'kpi', 'results', 'uptime'],
    build: statsSpec,
  },
  {
    id: 'quote-large',
    name: 'Pull quote',
    description: 'One large quote with attribution',
    category: 'proof',
    keywords: ['testimonial', 'quote', 'customer', 'single'],
    build: pullQuoteSpec,
  },
  {
    id: 'quote-portrait',
    name: 'Quote with portrait',
    description: 'A quote beside a photograph',
    category: 'proof',
    keywords: ['testimonial', 'photo', 'headshot', 'case study'],
    build: portraitQuoteSpec,
  },
  {
    id: 'case-studies',
    name: 'Case studies',
    description: 'Three cards, each led by a result',
    category: 'proof',
    keywords: ['results', 'customers', 'metrics', 'stories'],
    build: caseStudiesSpec,
  },
  {
    id: 'ratings',
    name: 'Rating badges',
    description: 'Review scores and certifications',
    category: 'proof',
    keywords: ['g2', 'reviews', 'stars', 'awards', 'soc 2'],
    build: ratingsSpec,
  },
  {
    id: 'pricing',
    name: 'Pricing',
    description: 'Three-tier pricing table',
    category: 'convert',
    keywords: ['plans', 'tiers', 'cost', 'subscribe'],
    build: pricingSpec,
  },
  {
    id: 'cta',
    name: 'Call to action',
    description: 'Full-width conversion panel',
    category: 'convert',
    keywords: ['signup', 'convert', 'banner', 'get started'],
    build: ctaSpec,
  },
  {
    id: 'cta-split',
    name: 'CTA with image',
    description: 'Copy and a photo side by side in one panel',
    category: 'convert',
    keywords: ['migrate', 'signup', 'panel', 'photo', 'convert'],
    build: ctaSplitSpec,
  },
  {
    id: 'faq',
    name: 'FAQ',
    description: 'Two-column question list',
    category: 'trust',
    keywords: ['questions', 'answers', 'help', 'support'],
    build: faqSpec,
  },
  {
    id: 'faq-accordion',
    name: 'FAQ accordion',
    description: 'Questions that open one at a time',
    category: 'trust',
    keywords: ['questions', 'answers', 'collapse', 'expand', 'disclosure', 'toggle'],
    build: faqAccordionSpec,
  },
  {
    id: 'team',
    name: 'Team grid',
    description: 'Portraits, names and roles',
    category: 'trust',
    keywords: ['people', 'about', 'staff', 'founders', 'leadership'],
    build: teamSpec,
  },
  {
    id: 'roles',
    name: 'Open roles',
    description: 'Job listings as a linked list',
    category: 'trust',
    keywords: ['careers', 'jobs', 'hiring', 'vacancies'],
    build: rolesSpec,
  },
  {
    id: 'prose',
    name: 'Prose page',
    description: 'Long-form document at a reading measure',
    category: 'trust',
    keywords: ['legal', 'privacy', 'terms', 'policy', 'article', 'text'],
    build: proseSpec,
  },
  {
    id: 'gallery',
    name: 'Gallery',
    description: 'Even grid of photographs',
    category: 'trust',
    keywords: ['photos', 'images', 'pictures', 'grid'],
    build: gallerySpec,
  },
  {
    id: 'gallery-masonry',
    name: 'Masonry gallery',
    description: 'Mixed shapes flowing down columns',
    category: 'trust',
    keywords: ['photos', 'images', 'pinterest', 'columns', 'mixed'],
    build: masonrySpec,
  },
  {
    id: 'blog-header',
    name: 'Blog header',
    description: 'Index title with topic filters',
    category: 'editorial',
    keywords: ['writing', 'index', 'tags', 'topics', 'categories'],
    build: blogHeaderSpec,
  },
  {
    id: 'post-featured',
    name: 'Featured post',
    description: 'One lead article beside its cover',
    category: 'editorial',
    keywords: ['blog', 'lead', 'hero', 'article', 'highlight'],
    build: featuredPostSpec,
  },
  {
    id: 'post-grid',
    name: 'Post grid',
    description: 'Three columns of article cards',
    category: 'editorial',
    keywords: ['blog', 'articles', 'news', 'index', 'cards'],
    build: postGridSpec,
  },
  {
    id: 'article',
    name: 'Article',
    description: 'Long-form piece with a sticky contents list',
    category: 'editorial',
    keywords: ['blog', 'post', 'toc', 'contents', 'writing'],
    build: articleSpec,
  },
  {
    id: 'author-card',
    name: 'Author card',
    description: 'Portrait, bio and links',
    category: 'editorial',
    keywords: ['byline', 'writer', 'bio', 'about the author'],
    build: authorCardSpec,
  },
  {
    id: 'related-posts',
    name: 'Related posts',
    description: 'Three more articles to keep reading',
    category: 'editorial',
    keywords: ['more', 'next', 'blog', 'recommended'],
    build: relatedPostsSpec,
  },
  {
    id: 'pagination',
    name: 'Pagination',
    description: 'Previous, next and numbered pages',
    category: 'editorial',
    keywords: ['pages', 'paging', 'next', 'previous', 'index'],
    build: paginationSpec,
  },
  {
    id: 'product-grid',
    name: 'Product grid',
    description: 'Collection of product cards with filters',
    category: 'commerce',
    keywords: ['shop', 'store', 'catalogue', 'collection', 'ecommerce'],
    build: productGridSpec,
  },
  {
    id: 'product-detail',
    name: 'Product detail',
    description: 'Gallery beside a buy box',
    category: 'commerce',
    keywords: ['pdp', 'buy', 'add to bag', 'shop', 'item'],
    build: productDetailSpec,
  },
  {
    id: 'cart',
    name: 'Cart summary',
    description: 'Line items with a running total',
    category: 'commerce',
    keywords: ['basket', 'bag', 'checkout', 'order', 'total'],
    build: cartSummarySpec,
  },
  {
    id: 'shipping-strip',
    name: 'Shipping strip',
    description: 'Delivery, returns and security promises',
    category: 'commerce',
    keywords: ['delivery', 'returns', 'trust', 'guarantee'],
    build: shippingStripSpec,
  },
  {
    id: 'app-shell',
    name: 'App shell',
    description: 'Sidebar, topbar and a content area',
    category: 'app',
    keywords: ['dashboard', 'sidebar', 'layout', 'admin', 'console'],
    build: appShellSpec,
  },
  {
    id: 'app-form',
    name: 'Form',
    description: 'Labelled fields with help and error text',
    category: 'app',
    keywords: ['input', 'fields', 'create', 'edit', 'settings'],
    build: formSpec,
  },
  {
    id: 'app-auth',
    name: 'Sign in',
    description: 'Centred authentication card',
    category: 'app',
    keywords: ['login', 'signup', 'password', 'account', 'auth'],
    build: authSpec,
  },
  {
    id: 'app-search',
    name: 'Search bar',
    description: 'Search field with filter controls',
    category: 'app',
    keywords: ['filter', 'find', 'toolbar', 'sort'],
    build: searchBarSpec,
  },
  {
    id: 'app-settings',
    name: 'Settings list',
    description: 'Rows of options with controls',
    category: 'app',
    keywords: ['preferences', 'options', 'admin', 'account'],
    build: settingsSpec,
  },
  {
    id: 'app-stats',
    name: 'Stat cards',
    description: 'Four metrics with deltas',
    category: 'app',
    keywords: ['kpi', 'metrics', 'dashboard', 'numbers'],
    build: statCardsSpec,
  },
  {
    id: 'app-members',
    name: 'Members',
    description: 'Team list with roles and avatars',
    category: 'app',
    keywords: ['team', 'users', 'people', 'permissions', 'seats'],
    build: membersSpec,
  },
  {
    id: 'app-badges',
    name: 'Badges',
    description: 'Status, plan and label pills',
    category: 'app',
    keywords: ['tags', 'pills', 'status', 'chips', 'labels'],
    build: badgesSpec,
  },
  {
    id: 'app-alerts',
    name: 'Alerts',
    description: 'Inline banners in three tones',
    category: 'app',
    keywords: ['banner', 'notice', 'warning', 'message', 'callout'],
    build: alertsSpec,
  },
  {
    id: 'app-notifications',
    name: 'Notifications',
    description: 'Activity list with unread markers',
    category: 'app',
    keywords: ['activity', 'inbox', 'feed', 'updates'],
    build: notificationsSpec,
  },
  {
    id: 'app-empty',
    name: 'Empty state',
    description: 'What to show before there is anything',
    category: 'app',
    keywords: ['zero state', 'onboarding', 'nothing', 'placeholder'],
    build: emptyStateSpec,
  },
  {
    id: 'app-skeleton',
    name: 'Skeleton',
    description: 'Loading placeholders shaped like the content',
    category: 'app',
    keywords: ['loading', 'shimmer', 'placeholder', 'pending'],
    build: skeletonSpec,
  },
  {
    id: 'app-files',
    name: 'File list',
    description: 'Uploaded resources with sizes and dates',
    category: 'app',
    keywords: ['documents', 'uploads', 'attachments', 'downloads'],
    build: fileListSpec,
  },
  {
    id: 'work-filter',
    name: 'Filterable work',
    description: 'A grid that filters by category, with an “Everything”',
    category: 'trust',
    keywords: ['portfolio', 'filter', 'category', 'gallery', 'case studies', 'switch'],
    build: workFilterSpec,
  },
  {
    id: 'app-stepper',
    name: 'Stepper',
    description: 'A form in three steps, one on screen at a time',
    category: 'app',
    keywords: ['wizard', 'onboarding', 'multi-step', 'checkout', 'flow', 'progress'],
    build: stepperSpec,
  },
  {
    id: 'docs-install',
    name: 'Install command',
    description: 'npm, pnpm, yarn and bun behind real tabs',
    category: 'editorial',
    keywords: ['code', 'terminal', 'package manager', 'docs', 'cli', 'tabs'],
    build: installTabsSpec,
  },
  {
    id: 'features-tabs',
    name: 'Tabbed features',
    description: 'Three panels behind real tabs — arrow keys and all',
    category: 'features',
    keywords: ['tabs', 'tabbed', 'switch', 'panels', 'stages', 'how it works'],
    build: tabbedFeaturesSpec,
  },
  {
    id: 'pricing-switch',
    name: 'Pricing with switch',
    description: 'Monthly and yearly prices, one click apart',
    category: 'convert',
    keywords: ['toggle', 'billing', 'annual', 'plans', 'tabs', 'switch'],
    build: pricingSwitchSpec,
  },
  {
    id: 'comparison',
    name: 'Comparison table',
    description: 'Plans compared feature by feature',
    category: 'convert',
    keywords: ['pricing', 'plans', 'matrix', 'table', 'versus'],
    build: comparisonSpec,
  },
  {
    id: 'app-data-table',
    name: 'Data table',
    description: 'Records with headers a screen reader can follow',
    category: 'app',
    keywords: ['table', 'rows', 'orders', 'records', 'grid', 'list'],
    build: dataTableSpec,
  },
  {
    id: 'app-filters',
    name: 'Filter panel',
    description: 'Sliders, checkboxes and radios in named groups',
    category: 'app',
    keywords: ['facets', 'refine', 'sidebar', 'catalogue', 'slider', 'fieldset'],
    build: filterPanelSpec,
  },
  {
    id: 'app-upload',
    name: 'Upload',
    description: 'File picker with per-file progress',
    category: 'app',
    keywords: ['import', 'files', 'drop zone', 'progress', 'attachment'],
    build: uploadSpec,
  },
  {
    id: 'app-confirm',
    name: 'Confirm dialog',
    description: 'A real <dialog>, announced as one, with no script',
    category: 'app',
    keywords: ['modal', 'confirm', 'delete', 'danger', 'alert', 'dialog'],
    build: confirmDialogSpec,
  },
  {
    id: 'app-command-menu',
    name: 'Command menu',
    description: 'A button opens a panel — no script on the page',
    category: 'app',
    keywords: ['popover', 'palette', 'dialog', 'menu', 'shortcut', 'modal'],
    build: commandMenuSpec,
  },
];
